[package]
name = "try_cargo_build"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = "0.23.1"
full_source.workspace = true
harvest_core.workspace = true
tracing.workspace = true

[lints]
workspace = true
